/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 39.4.5 Tue Jul  1 07:35:40 2025.
 */

#include <string.h>

#include "smart_wheels_hl.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

int smart_wheels_hl_head_light_left_btn_ctrl_pack(
    uint8_t *dst_p,
    const struct smart_wheels_hl_head_light_left_btn_ctrl_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->head_light_beam, 0u, 0x03u);
    dst_p[0] |= pack_left_shift_u8(src_p->head_light_level, 2u, 0x1cu);
    dst_p[0] |= pack_left_shift_u8(src_p->indicator_light, 5u, 0x20u);
    dst_p[0] |= pack_left_shift_u8(src_p->parking_light, 6u, 0x40u);

    return (1);
}

int smart_wheels_hl_head_light_left_btn_ctrl_unpack(
    struct smart_wheels_hl_head_light_left_btn_ctrl_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->head_light_beam = unpack_right_shift_u8(src_p[0], 0u, 0x03u);
    dst_p->head_light_level = unpack_right_shift_u8(src_p[0], 2u, 0x1cu);
    dst_p->indicator_light = unpack_right_shift_u8(src_p[0], 5u, 0x20u);
    dst_p->parking_light = unpack_right_shift_u8(src_p[0], 6u, 0x40u);

    return (0);
}

int smart_wheels_hl_head_light_left_btn_ctrl_init(struct smart_wheels_hl_head_light_left_btn_ctrl_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct smart_wheels_hl_head_light_left_btn_ctrl_t));

    return 0;
}

uint8_t smart_wheels_hl_head_light_left_btn_ctrl_head_light_beam_encode(double value)
{
    return (uint8_t)(value);
}

double smart_wheels_hl_head_light_left_btn_ctrl_head_light_beam_decode(uint8_t value)
{
    return ((double)value);
}

bool smart_wheels_hl_head_light_left_btn_ctrl_head_light_beam_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t smart_wheels_hl_head_light_left_btn_ctrl_head_light_level_encode(double value)
{
    return (uint8_t)(value);
}

double smart_wheels_hl_head_light_left_btn_ctrl_head_light_level_decode(uint8_t value)
{
    return ((double)value);
}

bool smart_wheels_hl_head_light_left_btn_ctrl_head_light_level_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t smart_wheels_hl_head_light_left_btn_ctrl_indicator_light_encode(double value)
{
    return (uint8_t)(value);
}

double smart_wheels_hl_head_light_left_btn_ctrl_indicator_light_decode(uint8_t value)
{
    return ((double)value);
}

bool smart_wheels_hl_head_light_left_btn_ctrl_indicator_light_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t smart_wheels_hl_head_light_left_btn_ctrl_parking_light_encode(double value)
{
    return (uint8_t)(value);
}

double smart_wheels_hl_head_light_left_btn_ctrl_parking_light_decode(uint8_t value)
{
    return ((double)value);
}

bool smart_wheels_hl_head_light_left_btn_ctrl_parking_light_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int smart_wheels_hl_head_light_right_btn_ctrl_pack(
    uint8_t *dst_p,
    const struct smart_wheels_hl_head_light_right_btn_ctrl_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->head_light_beam, 0u, 0x03u);
    dst_p[0] |= pack_left_shift_u8(src_p->head_light_level, 2u, 0x1cu);
    dst_p[0] |= pack_left_shift_u8(src_p->indicator_light, 5u, 0x20u);
    dst_p[0] |= pack_left_shift_u8(src_p->parking_light, 6u, 0x40u);

    return (1);
}

int smart_wheels_hl_head_light_right_btn_ctrl_unpack(
    struct smart_wheels_hl_head_light_right_btn_ctrl_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->head_light_beam = unpack_right_shift_u8(src_p[0], 0u, 0x03u);
    dst_p->head_light_level = unpack_right_shift_u8(src_p[0], 2u, 0x1cu);
    dst_p->indicator_light = unpack_right_shift_u8(src_p[0], 5u, 0x20u);
    dst_p->parking_light = unpack_right_shift_u8(src_p[0], 6u, 0x40u);

    return (0);
}

int smart_wheels_hl_head_light_right_btn_ctrl_init(struct smart_wheels_hl_head_light_right_btn_ctrl_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct smart_wheels_hl_head_light_right_btn_ctrl_t));

    return 0;
}

uint8_t smart_wheels_hl_head_light_right_btn_ctrl_head_light_beam_encode(double value)
{
    return (uint8_t)(value);
}

double smart_wheels_hl_head_light_right_btn_ctrl_head_light_beam_decode(uint8_t value)
{
    return ((double)value);
}

bool smart_wheels_hl_head_light_right_btn_ctrl_head_light_beam_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t smart_wheels_hl_head_light_right_btn_ctrl_head_light_level_encode(double value)
{
    return (uint8_t)(value);
}

double smart_wheels_hl_head_light_right_btn_ctrl_head_light_level_decode(uint8_t value)
{
    return ((double)value);
}

bool smart_wheels_hl_head_light_right_btn_ctrl_head_light_level_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t smart_wheels_hl_head_light_right_btn_ctrl_indicator_light_encode(double value)
{
    return (uint8_t)(value);
}

double smart_wheels_hl_head_light_right_btn_ctrl_indicator_light_decode(uint8_t value)
{
    return ((double)value);
}

bool smart_wheels_hl_head_light_right_btn_ctrl_indicator_light_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t smart_wheels_hl_head_light_right_btn_ctrl_parking_light_encode(double value)
{
    return (uint8_t)(value);
}

double smart_wheels_hl_head_light_right_btn_ctrl_parking_light_decode(uint8_t value)
{
    return ((double)value);
}

bool smart_wheels_hl_head_light_right_btn_ctrl_parking_light_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int smart_wheels_hl_head_light_left_sdv_ctrl_pack(
    uint8_t *dst_p,
    const struct smart_wheels_hl_head_light_left_sdv_ctrl_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->head_light_beam, 0u, 0x03u);
    dst_p[0] |= pack_left_shift_u8(src_p->head_light_level, 2u, 0x1cu);
    dst_p[0] |= pack_left_shift_u8(src_p->indicator_light, 5u, 0x20u);
    dst_p[0] |= pack_left_shift_u8(src_p->parking_light, 6u, 0x40u);

    return (1);
}

int smart_wheels_hl_head_light_left_sdv_ctrl_unpack(
    struct smart_wheels_hl_head_light_left_sdv_ctrl_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->head_light_beam = unpack_right_shift_u8(src_p[0], 0u, 0x03u);
    dst_p->head_light_level = unpack_right_shift_u8(src_p[0], 2u, 0x1cu);
    dst_p->indicator_light = unpack_right_shift_u8(src_p[0], 5u, 0x20u);
    dst_p->parking_light = unpack_right_shift_u8(src_p[0], 6u, 0x40u);

    return (0);
}

int smart_wheels_hl_head_light_left_sdv_ctrl_init(struct smart_wheels_hl_head_light_left_sdv_ctrl_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct smart_wheels_hl_head_light_left_sdv_ctrl_t));

    return 0;
}

uint8_t smart_wheels_hl_head_light_left_sdv_ctrl_head_light_beam_encode(double value)
{
    return (uint8_t)(value);
}

double smart_wheels_hl_head_light_left_sdv_ctrl_head_light_beam_decode(uint8_t value)
{
    return ((double)value);
}

bool smart_wheels_hl_head_light_left_sdv_ctrl_head_light_beam_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t smart_wheels_hl_head_light_left_sdv_ctrl_head_light_level_encode(double value)
{
    return (uint8_t)(value);
}

double smart_wheels_hl_head_light_left_sdv_ctrl_head_light_level_decode(uint8_t value)
{
    return ((double)value);
}

bool smart_wheels_hl_head_light_left_sdv_ctrl_head_light_level_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t smart_wheels_hl_head_light_left_sdv_ctrl_indicator_light_encode(double value)
{
    return (uint8_t)(value);
}

double smart_wheels_hl_head_light_left_sdv_ctrl_indicator_light_decode(uint8_t value)
{
    return ((double)value);
}

bool smart_wheels_hl_head_light_left_sdv_ctrl_indicator_light_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t smart_wheels_hl_head_light_left_sdv_ctrl_parking_light_encode(double value)
{
    return (uint8_t)(value);
}

double smart_wheels_hl_head_light_left_sdv_ctrl_parking_light_decode(uint8_t value)
{
    return ((double)value);
}

bool smart_wheels_hl_head_light_left_sdv_ctrl_parking_light_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int smart_wheels_hl_head_light_right_sdv_ctrl_pack(
    uint8_t *dst_p,
    const struct smart_wheels_hl_head_light_right_sdv_ctrl_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->head_light_beam, 0u, 0x03u);
    dst_p[0] |= pack_left_shift_u8(src_p->head_light_level, 2u, 0x1cu);
    dst_p[0] |= pack_left_shift_u8(src_p->indicator_light, 5u, 0x20u);
    dst_p[0] |= pack_left_shift_u8(src_p->parking_light, 6u, 0x40u);

    return (1);
}

int smart_wheels_hl_head_light_right_sdv_ctrl_unpack(
    struct smart_wheels_hl_head_light_right_sdv_ctrl_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->head_light_beam = unpack_right_shift_u8(src_p[0], 0u, 0x03u);
    dst_p->head_light_level = unpack_right_shift_u8(src_p[0], 2u, 0x1cu);
    dst_p->indicator_light = unpack_right_shift_u8(src_p[0], 5u, 0x20u);
    dst_p->parking_light = unpack_right_shift_u8(src_p[0], 6u, 0x40u);

    return (0);
}

int smart_wheels_hl_head_light_right_sdv_ctrl_init(struct smart_wheels_hl_head_light_right_sdv_ctrl_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct smart_wheels_hl_head_light_right_sdv_ctrl_t));

    return 0;
}

uint8_t smart_wheels_hl_head_light_right_sdv_ctrl_head_light_beam_encode(double value)
{
    return (uint8_t)(value);
}

double smart_wheels_hl_head_light_right_sdv_ctrl_head_light_beam_decode(uint8_t value)
{
    return ((double)value);
}

bool smart_wheels_hl_head_light_right_sdv_ctrl_head_light_beam_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t smart_wheels_hl_head_light_right_sdv_ctrl_head_light_level_encode(double value)
{
    return (uint8_t)(value);
}

double smart_wheels_hl_head_light_right_sdv_ctrl_head_light_level_decode(uint8_t value)
{
    return ((double)value);
}

bool smart_wheels_hl_head_light_right_sdv_ctrl_head_light_level_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t smart_wheels_hl_head_light_right_sdv_ctrl_indicator_light_encode(double value)
{
    return (uint8_t)(value);
}

double smart_wheels_hl_head_light_right_sdv_ctrl_indicator_light_decode(uint8_t value)
{
    return ((double)value);
}

bool smart_wheels_hl_head_light_right_sdv_ctrl_indicator_light_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t smart_wheels_hl_head_light_right_sdv_ctrl_parking_light_encode(double value)
{
    return (uint8_t)(value);
}

double smart_wheels_hl_head_light_right_sdv_ctrl_parking_light_decode(uint8_t value)
{
    return ((double)value);
}

bool smart_wheels_hl_head_light_right_sdv_ctrl_parking_light_is_in_range(uint8_t value)
{
    return (value <= 1u);
}
