; platformio.ini — SmartWheels ESP32-WROOM FOTAmatics
; Merged: FOTA/Bootloader + Telematics (CAN→MQTT gateway)

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
upload_protocol = esptool
upload_port = COM12
upload_speed = 921600
monitor_port = COM12
monitor_speed = 921600
monitor_filters = esp32_exception_decoder
board_build.partitions = partitions_custom.csv
board_build.flash_mode = qio
board_build.f_flash = 80000000L

build_flags =
    -Iinclude
    -D CONFIG_NIMBLE_TASK_STACK_SIZE=5120
    -D CONFIG_BT_NIMBLE_TASK_STACK_SIZE=5120
    -D CONFIG_ASYNC_TCP_MAX_ACK_TIME=3000
    -D CONFIG_ASYNC_TCP_PRIORITY=10
    -D CONFIG_ASYNC_TCP_QUEUE_SIZE=32
    -D CONFIG_ASYNC_TCP_RUNNING_CORE=1
    -D CONFIG_ASYNC_TCP_STACK_SIZE=4096
    -D MQTT_MAX_PACKET_SIZE=8192

lib_deps =
    me-no-dev/ESPAsyncWebServer@3.6.0
    me-no-dev/AsyncTCP@3.3.2
    ArduinoJson@7.4.1
    fbiego/ESP32Time@2.0.6
    adafruit/Adafruit BusIO@1.17.1
    adafruit/RTClib@2.1.4
    https://github.com/emelianov/modbus-esp8266@4.1.0+sha.73f1911
    knolleary/PubSubClient@^2.8
    h2zero/NimBLE-Arduino@^1.4.1
