/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 39.4.5 Tue Jul  1 07:35:40 2025.
 */

#ifndef SMART_WHEELS_HL_H
#define SMART_WHEELS_HL_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define SMART_WHEELS_HL_HEAD_LIGHT_LEFT_BTN_CTRL_FRAME_ID (0x321u)
#define SMART_WHEELS_HL_HEAD_LIGHT_RIGHT_BTN_CTRL_FRAME_ID (0x322u)
#define SMART_WHEELS_HL_HEAD_LIGHT_LEFT_SDV_CTRL_FRAME_ID (0x325u)
#define SMART_WHEELS_HL_HEAD_LIGHT_RIGHT_SDV_CTRL_FRAME_ID (0x326u)

/* Frame lengths in bytes. */
#define SMART_WHEELS_HL_HEAD_LIGHT_LEFT_BTN_CTRL_LENGTH (1u)
#define SMART_WHEELS_HL_HEAD_LIGHT_RIGHT_BTN_CTRL_LENGTH (1u)
#define SMART_WHEELS_HL_HEAD_LIGHT_LEFT_SDV_CTRL_LENGTH (1u)
#define SMART_WHEELS_HL_HEAD_LIGHT_RIGHT_SDV_CTRL_LENGTH (1u)

/* Extended or standard frame types. */
#define SMART_WHEELS_HL_HEAD_LIGHT_LEFT_BTN_CTRL_IS_EXTENDED (0)
#define SMART_WHEELS_HL_HEAD_LIGHT_RIGHT_BTN_CTRL_IS_EXTENDED (0)
#define SMART_WHEELS_HL_HEAD_LIGHT_LEFT_SDV_CTRL_IS_EXTENDED (0)
#define SMART_WHEELS_HL_HEAD_LIGHT_RIGHT_SDV_CTRL_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */
#define SMART_WHEELS_HL_HEAD_LIGHT_LEFT_BTN_CTRL_CYCLE_TIME_MS (100u)
#define SMART_WHEELS_HL_HEAD_LIGHT_RIGHT_BTN_CTRL_CYCLE_TIME_MS (100u)
#define SMART_WHEELS_HL_HEAD_LIGHT_LEFT_SDV_CTRL_CYCLE_TIME_MS (100u)
#define SMART_WHEELS_HL_HEAD_LIGHT_RIGHT_SDV_CTRL_CYCLE_TIME_MS (100u)

/* Signal choices. */
#define SMART_WHEELS_HL_HEAD_LIGHT_LEFT_BTN_CTRL_HEAD_LIGHT_BEAM_HL_BEAM_OFF_CHOICE (0u)
#define SMART_WHEELS_HL_HEAD_LIGHT_LEFT_BTN_CTRL_HEAD_LIGHT_BEAM_HL_BEAM_LOW_CHOICE (1u)
#define SMART_WHEELS_HL_HEAD_LIGHT_LEFT_BTN_CTRL_HEAD_LIGHT_BEAM_HL_BEAM_HIGH_CHOICE (2u)

#define SMART_WHEELS_HL_HEAD_LIGHT_LEFT_BTN_CTRL_HEAD_LIGHT_LEVEL_LEVELLER_POS_0_CHOICE (0u)
#define SMART_WHEELS_HL_HEAD_LIGHT_LEFT_BTN_CTRL_HEAD_LIGHT_LEVEL_LEVELLER_POS_1_CHOICE (1u)
#define SMART_WHEELS_HL_HEAD_LIGHT_LEFT_BTN_CTRL_HEAD_LIGHT_LEVEL_LEVELLER_POS_2_CHOICE (2u)
#define SMART_WHEELS_HL_HEAD_LIGHT_LEFT_BTN_CTRL_HEAD_LIGHT_LEVEL_LEVELLER_POS_3_CHOICE (3u)
#define SMART_WHEELS_HL_HEAD_LIGHT_LEFT_BTN_CTRL_HEAD_LIGHT_LEVEL_LEVELLER_POS_4_CHOICE (4u)

#define SMART_WHEELS_HL_HEAD_LIGHT_LEFT_BTN_CTRL_INDICATOR_LIGHT_OFF_CHOICE (0u)
#define SMART_WHEELS_HL_HEAD_LIGHT_LEFT_BTN_CTRL_INDICATOR_LIGHT_ON_CHOICE (1u)

#define SMART_WHEELS_HL_HEAD_LIGHT_LEFT_BTN_CTRL_PARKING_LIGHT_OFF_CHOICE (0u)
#define SMART_WHEELS_HL_HEAD_LIGHT_LEFT_BTN_CTRL_PARKING_LIGHT_ON_CHOICE (1u)

#define SMART_WHEELS_HL_HEAD_LIGHT_RIGHT_BTN_CTRL_HEAD_LIGHT_BEAM_HL_BEAM_OFF_CHOICE (0u)
#define SMART_WHEELS_HL_HEAD_LIGHT_RIGHT_BTN_CTRL_HEAD_LIGHT_BEAM_HL_BEAM_LOW_CHOICE (1u)
#define SMART_WHEELS_HL_HEAD_LIGHT_RIGHT_BTN_CTRL_HEAD_LIGHT_BEAM_HL_BEAM_HIGH_CHOICE (2u)

#define SMART_WHEELS_HL_HEAD_LIGHT_RIGHT_BTN_CTRL_HEAD_LIGHT_LEVEL_LEVELLER_POS_0_CHOICE (0u)
#define SMART_WHEELS_HL_HEAD_LIGHT_RIGHT_BTN_CTRL_HEAD_LIGHT_LEVEL_LEVELLER_POS_1_CHOICE (1u)
#define SMART_WHEELS_HL_HEAD_LIGHT_RIGHT_BTN_CTRL_HEAD_LIGHT_LEVEL_LEVELLER_POS_2_CHOICE (2u)
#define SMART_WHEELS_HL_HEAD_LIGHT_RIGHT_BTN_CTRL_HEAD_LIGHT_LEVEL_LEVELLER_POS_3_CHOICE (3u)
#define SMART_WHEELS_HL_HEAD_LIGHT_RIGHT_BTN_CTRL_HEAD_LIGHT_LEVEL_LEVELLER_POS_4_CHOICE (4u)

#define SMART_WHEELS_HL_HEAD_LIGHT_RIGHT_BTN_CTRL_INDICATOR_LIGHT_OFF_CHOICE (0u)
#define SMART_WHEELS_HL_HEAD_LIGHT_RIGHT_BTN_CTRL_INDICATOR_LIGHT_ON_CHOICE (1u)

#define SMART_WHEELS_HL_HEAD_LIGHT_RIGHT_BTN_CTRL_PARKING_LIGHT_OFF_CHOICE (0u)
#define SMART_WHEELS_HL_HEAD_LIGHT_RIGHT_BTN_CTRL_PARKING_LIGHT_ON_CHOICE (1u)

#define SMART_WHEELS_HL_HEAD_LIGHT_LEFT_SDV_CTRL_HEAD_LIGHT_BEAM_HL_BEAM_OFF_CHOICE (0u)
#define SMART_WHEELS_HL_HEAD_LIGHT_LEFT_SDV_CTRL_HEAD_LIGHT_BEAM_HL_BEAM_LOW_CHOICE (1u)
#define SMART_WHEELS_HL_HEAD_LIGHT_LEFT_SDV_CTRL_HEAD_LIGHT_BEAM_HL_BEAM_HIGH_CHOICE (2u)

#define SMART_WHEELS_HL_HEAD_LIGHT_LEFT_SDV_CTRL_HEAD_LIGHT_LEVEL_LEVELLER_POS_0_CHOICE (0u)
#define SMART_WHEELS_HL_HEAD_LIGHT_LEFT_SDV_CTRL_HEAD_LIGHT_LEVEL_LEVELLER_POS_1_CHOICE (1u)
#define SMART_WHEELS_HL_HEAD_LIGHT_LEFT_SDV_CTRL_HEAD_LIGHT_LEVEL_LEVELLER_POS_2_CHOICE (2u)
#define SMART_WHEELS_HL_HEAD_LIGHT_LEFT_SDV_CTRL_HEAD_LIGHT_LEVEL_LEVELLER_POS_3_CHOICE (3u)
#define SMART_WHEELS_HL_HEAD_LIGHT_LEFT_SDV_CTRL_HEAD_LIGHT_LEVEL_LEVELLER_POS_4_CHOICE (4u)

#define SMART_WHEELS_HL_HEAD_LIGHT_LEFT_SDV_CTRL_INDICATOR_LIGHT_OFF_CHOICE (0u)
#define SMART_WHEELS_HL_HEAD_LIGHT_LEFT_SDV_CTRL_INDICATOR_LIGHT_ON_CHOICE (1u)

#define SMART_WHEELS_HL_HEAD_LIGHT_LEFT_SDV_CTRL_PARKING_LIGHT_OFF_CHOICE (0u)
#define SMART_WHEELS_HL_HEAD_LIGHT_LEFT_SDV_CTRL_PARKING_LIGHT_ON_CHOICE (1u)

#define SMART_WHEELS_HL_HEAD_LIGHT_RIGHT_SDV_CTRL_HEAD_LIGHT_BEAM_HL_BEAM_OFF_CHOICE (0u)
#define SMART_WHEELS_HL_HEAD_LIGHT_RIGHT_SDV_CTRL_HEAD_LIGHT_BEAM_HL_BEAM_LOW_CHOICE (1u)
#define SMART_WHEELS_HL_HEAD_LIGHT_RIGHT_SDV_CTRL_HEAD_LIGHT_BEAM_HL_BEAM_HIGH_CHOICE (2u)

#define SMART_WHEELS_HL_HEAD_LIGHT_RIGHT_SDV_CTRL_HEAD_LIGHT_LEVEL_LEVELLER_POS_0_CHOICE (0u)
#define SMART_WHEELS_HL_HEAD_LIGHT_RIGHT_SDV_CTRL_HEAD_LIGHT_LEVEL_LEVELLER_POS_1_CHOICE (1u)
#define SMART_WHEELS_HL_HEAD_LIGHT_RIGHT_SDV_CTRL_HEAD_LIGHT_LEVEL_LEVELLER_POS_2_CHOICE (2u)
#define SMART_WHEELS_HL_HEAD_LIGHT_RIGHT_SDV_CTRL_HEAD_LIGHT_LEVEL_LEVELLER_POS_3_CHOICE (3u)
#define SMART_WHEELS_HL_HEAD_LIGHT_RIGHT_SDV_CTRL_HEAD_LIGHT_LEVEL_LEVELLER_POS_4_CHOICE (4u)

#define SMART_WHEELS_HL_HEAD_LIGHT_RIGHT_SDV_CTRL_INDICATOR_LIGHT_OFF_CHOICE (0u)
#define SMART_WHEELS_HL_HEAD_LIGHT_RIGHT_SDV_CTRL_INDICATOR_LIGHT_ON_CHOICE (1u)

#define SMART_WHEELS_HL_HEAD_LIGHT_RIGHT_SDV_CTRL_PARKING_LIGHT_OFF_CHOICE (0u)
#define SMART_WHEELS_HL_HEAD_LIGHT_RIGHT_SDV_CTRL_PARKING_LIGHT_ON_CHOICE (1u)

/* Frame Names. */
#define SMART_WHEELS_HL_HEAD_LIGHT_LEFT_BTN_CTRL_NAME "head_light_left_btn_ctrl"
#define SMART_WHEELS_HL_HEAD_LIGHT_RIGHT_BTN_CTRL_NAME "head_light_right_btn_ctrl"
#define SMART_WHEELS_HL_HEAD_LIGHT_LEFT_SDV_CTRL_NAME "head_light_left_sdv_ctrl"
#define SMART_WHEELS_HL_HEAD_LIGHT_RIGHT_SDV_CTRL_NAME "head_light_right_sdv_ctrl"

/* Signal Names. */
#define SMART_WHEELS_HL_HEAD_LIGHT_LEFT_BTN_CTRL_HEAD_LIGHT_BEAM_NAME "head_light_beam"
#define SMART_WHEELS_HL_HEAD_LIGHT_LEFT_BTN_CTRL_HEAD_LIGHT_LEVEL_NAME "head_light_level"
#define SMART_WHEELS_HL_HEAD_LIGHT_LEFT_BTN_CTRL_INDICATOR_LIGHT_NAME "indicator_light"
#define SMART_WHEELS_HL_HEAD_LIGHT_LEFT_BTN_CTRL_PARKING_LIGHT_NAME "parking_light"
#define SMART_WHEELS_HL_HEAD_LIGHT_RIGHT_BTN_CTRL_HEAD_LIGHT_BEAM_NAME "head_light_beam"
#define SMART_WHEELS_HL_HEAD_LIGHT_RIGHT_BTN_CTRL_HEAD_LIGHT_LEVEL_NAME "head_light_level"
#define SMART_WHEELS_HL_HEAD_LIGHT_RIGHT_BTN_CTRL_INDICATOR_LIGHT_NAME "indicator_light"
#define SMART_WHEELS_HL_HEAD_LIGHT_RIGHT_BTN_CTRL_PARKING_LIGHT_NAME "parking_light"
#define SMART_WHEELS_HL_HEAD_LIGHT_LEFT_SDV_CTRL_HEAD_LIGHT_BEAM_NAME "head_light_beam"
#define SMART_WHEELS_HL_HEAD_LIGHT_LEFT_SDV_CTRL_HEAD_LIGHT_LEVEL_NAME "head_light_level"
#define SMART_WHEELS_HL_HEAD_LIGHT_LEFT_SDV_CTRL_INDICATOR_LIGHT_NAME "indicator_light"
#define SMART_WHEELS_HL_HEAD_LIGHT_LEFT_SDV_CTRL_PARKING_LIGHT_NAME "parking_light"
#define SMART_WHEELS_HL_HEAD_LIGHT_RIGHT_SDV_CTRL_HEAD_LIGHT_BEAM_NAME "head_light_beam"
#define SMART_WHEELS_HL_HEAD_LIGHT_RIGHT_SDV_CTRL_HEAD_LIGHT_LEVEL_NAME "head_light_level"
#define SMART_WHEELS_HL_HEAD_LIGHT_RIGHT_SDV_CTRL_INDICATOR_LIGHT_NAME "indicator_light"
#define SMART_WHEELS_HL_HEAD_LIGHT_RIGHT_SDV_CTRL_PARKING_LIGHT_NAME "parking_light"

/**
 * Signals in message head_light_left_btn_ctrl.
 *
 * AI_10V_Status
 *
 * All signal values are as on the CAN bus.
 */
struct smart_wheels_hl_head_light_left_btn_ctrl_t {
    /**
     * Range: 0..3 (0..3 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t head_light_beam;

    /**
     * Range: 0..7 (0..7 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t head_light_level;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t indicator_light;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t parking_light;
};

/**
 * Signals in message head_light_right_btn_ctrl.
 *
 * AI_10V_Status
 *
 * All signal values are as on the CAN bus.
 */
struct smart_wheels_hl_head_light_right_btn_ctrl_t {
    /**
     * Range: 0..3 (0..3 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t head_light_beam;

    /**
     * Range: 0..7 (0..7 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t head_light_level;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t indicator_light;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t parking_light;
};

/**
 * Signals in message head_light_left_sdv_ctrl.
 *
 * AI_10V_Status
 *
 * All signal values are as on the CAN bus.
 */
struct smart_wheels_hl_head_light_left_sdv_ctrl_t {
    /**
     * Range: 0..3 (0..3 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t head_light_beam;

    /**
     * Range: 0..7 (0..7 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t head_light_level;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t indicator_light;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t parking_light;
};

/**
 * Signals in message head_light_right_sdv_ctrl.
 *
 * AI_10V_Status
 *
 * All signal values are as on the CAN bus.
 */
struct smart_wheels_hl_head_light_right_sdv_ctrl_t {
    /**
     * Range: 0..3 (0..3 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t head_light_beam;

    /**
     * Range: 0..7 (0..7 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t head_light_level;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t indicator_light;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t parking_light;
};

/**
 * Pack message head_light_left_btn_ctrl.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int smart_wheels_hl_head_light_left_btn_ctrl_pack(
    uint8_t *dst_p,
    const struct smart_wheels_hl_head_light_left_btn_ctrl_t *src_p,
    size_t size);

/**
 * Unpack message head_light_left_btn_ctrl.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int smart_wheels_hl_head_light_left_btn_ctrl_unpack(
    struct smart_wheels_hl_head_light_left_btn_ctrl_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from head_light_left_btn_ctrl.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int smart_wheels_hl_head_light_left_btn_ctrl_init(struct smart_wheels_hl_head_light_left_btn_ctrl_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t smart_wheels_hl_head_light_left_btn_ctrl_head_light_beam_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double smart_wheels_hl_head_light_left_btn_ctrl_head_light_beam_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool smart_wheels_hl_head_light_left_btn_ctrl_head_light_beam_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t smart_wheels_hl_head_light_left_btn_ctrl_head_light_level_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double smart_wheels_hl_head_light_left_btn_ctrl_head_light_level_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool smart_wheels_hl_head_light_left_btn_ctrl_head_light_level_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t smart_wheels_hl_head_light_left_btn_ctrl_indicator_light_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double smart_wheels_hl_head_light_left_btn_ctrl_indicator_light_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool smart_wheels_hl_head_light_left_btn_ctrl_indicator_light_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t smart_wheels_hl_head_light_left_btn_ctrl_parking_light_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double smart_wheels_hl_head_light_left_btn_ctrl_parking_light_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool smart_wheels_hl_head_light_left_btn_ctrl_parking_light_is_in_range(uint8_t value);

/**
 * Pack message head_light_right_btn_ctrl.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int smart_wheels_hl_head_light_right_btn_ctrl_pack(
    uint8_t *dst_p,
    const struct smart_wheels_hl_head_light_right_btn_ctrl_t *src_p,
    size_t size);

/**
 * Unpack message head_light_right_btn_ctrl.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int smart_wheels_hl_head_light_right_btn_ctrl_unpack(
    struct smart_wheels_hl_head_light_right_btn_ctrl_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from head_light_right_btn_ctrl.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int smart_wheels_hl_head_light_right_btn_ctrl_init(struct smart_wheels_hl_head_light_right_btn_ctrl_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t smart_wheels_hl_head_light_right_btn_ctrl_head_light_beam_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double smart_wheels_hl_head_light_right_btn_ctrl_head_light_beam_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool smart_wheels_hl_head_light_right_btn_ctrl_head_light_beam_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t smart_wheels_hl_head_light_right_btn_ctrl_head_light_level_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double smart_wheels_hl_head_light_right_btn_ctrl_head_light_level_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool smart_wheels_hl_head_light_right_btn_ctrl_head_light_level_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t smart_wheels_hl_head_light_right_btn_ctrl_indicator_light_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double smart_wheels_hl_head_light_right_btn_ctrl_indicator_light_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool smart_wheels_hl_head_light_right_btn_ctrl_indicator_light_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t smart_wheels_hl_head_light_right_btn_ctrl_parking_light_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double smart_wheels_hl_head_light_right_btn_ctrl_parking_light_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool smart_wheels_hl_head_light_right_btn_ctrl_parking_light_is_in_range(uint8_t value);

/**
 * Pack message head_light_left_sdv_ctrl.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int smart_wheels_hl_head_light_left_sdv_ctrl_pack(
    uint8_t *dst_p,
    const struct smart_wheels_hl_head_light_left_sdv_ctrl_t *src_p,
    size_t size);

/**
 * Unpack message head_light_left_sdv_ctrl.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int smart_wheels_hl_head_light_left_sdv_ctrl_unpack(
    struct smart_wheels_hl_head_light_left_sdv_ctrl_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from head_light_left_sdv_ctrl.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int smart_wheels_hl_head_light_left_sdv_ctrl_init(struct smart_wheels_hl_head_light_left_sdv_ctrl_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t smart_wheels_hl_head_light_left_sdv_ctrl_head_light_beam_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double smart_wheels_hl_head_light_left_sdv_ctrl_head_light_beam_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool smart_wheels_hl_head_light_left_sdv_ctrl_head_light_beam_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t smart_wheels_hl_head_light_left_sdv_ctrl_head_light_level_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double smart_wheels_hl_head_light_left_sdv_ctrl_head_light_level_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool smart_wheels_hl_head_light_left_sdv_ctrl_head_light_level_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t smart_wheels_hl_head_light_left_sdv_ctrl_indicator_light_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double smart_wheels_hl_head_light_left_sdv_ctrl_indicator_light_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool smart_wheels_hl_head_light_left_sdv_ctrl_indicator_light_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t smart_wheels_hl_head_light_left_sdv_ctrl_parking_light_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double smart_wheels_hl_head_light_left_sdv_ctrl_parking_light_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool smart_wheels_hl_head_light_left_sdv_ctrl_parking_light_is_in_range(uint8_t value);

/**
 * Pack message head_light_right_sdv_ctrl.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int smart_wheels_hl_head_light_right_sdv_ctrl_pack(
    uint8_t *dst_p,
    const struct smart_wheels_hl_head_light_right_sdv_ctrl_t *src_p,
    size_t size);

/**
 * Unpack message head_light_right_sdv_ctrl.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int smart_wheels_hl_head_light_right_sdv_ctrl_unpack(
    struct smart_wheels_hl_head_light_right_sdv_ctrl_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from head_light_right_sdv_ctrl.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int smart_wheels_hl_head_light_right_sdv_ctrl_init(struct smart_wheels_hl_head_light_right_sdv_ctrl_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t smart_wheels_hl_head_light_right_sdv_ctrl_head_light_beam_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double smart_wheels_hl_head_light_right_sdv_ctrl_head_light_beam_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool smart_wheels_hl_head_light_right_sdv_ctrl_head_light_beam_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t smart_wheels_hl_head_light_right_sdv_ctrl_head_light_level_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double smart_wheels_hl_head_light_right_sdv_ctrl_head_light_level_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool smart_wheels_hl_head_light_right_sdv_ctrl_head_light_level_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t smart_wheels_hl_head_light_right_sdv_ctrl_indicator_light_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double smart_wheels_hl_head_light_right_sdv_ctrl_indicator_light_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool smart_wheels_hl_head_light_right_sdv_ctrl_indicator_light_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t smart_wheels_hl_head_light_right_sdv_ctrl_parking_light_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double smart_wheels_hl_head_light_right_sdv_ctrl_parking_light_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool smart_wheels_hl_head_light_right_sdv_ctrl_parking_light_is_in_range(uint8_t value);


#ifdef __cplusplus
}
#endif

#endif
