/*
 * genx_simulink_bridge.h
 * Auto-generated by SmartWheels GenX â€” DO NOT EDIT
 * Model : ACC
 * Date  : 2026-05-08
 */

#ifndef GENX_SIMULINK_BRIDGE_H
#define GENX_SIMULINK_BRIDGE_H

#ifdef __cplusplus
extern "C" {
#endif

/* Include the Simulink-generated header */
#include "ACC.h"

/**
 * Copy BSW signal values into ExtU (inputs to Simulink model).
 * Call this BEFORE ACC_step().
 */
void ANCIT_App_PreStep(void);

/**
 * Read ExtY (outputs from Simulink model) and write to BSW signals.
 * Call this AFTER ACC_step().
 */
void ANCIT_App_PostStep(void);

/**
 * Call ACC_initialize() â€” invoke once during board initialisation.
 */
void ANCIT_App_Init(void);

#ifdef __cplusplus
}
#endif

#endif /* GENX_SIMULINK_BRIDGE_H */
