/*
 * genx_simulink_bridge.c
 * Auto-generated by SmartWheels GenX Ã¢â‚¬â€� DO NOT EDIT
 * Model : ACC
 * Date  : 2026-05-08
 */

#include "genx_simulink_bridge.h"
#include "genx_common.h"


/* -------------------------------------------------------------- */
void ANCIT_App_Init(void)
{
    ACC_initialize();
}

/* -------------------------------------------------------------- */
void ANCIT_App_PreStep(void)
{
    ACC_U.Distance = ((real_T)(ggenx.Distance));
    ACC_U.V_set = ((real_T)(ggenx.V_set));
    ACC_U.D_min = ((real_T)(ggenx.D_min));
}

/* -------------------------------------------------------------- */
void ANCIT_App_PostStep(void)
{
    ggenx.PWM = ACC_Y.PWM;
}

/*
 * Scheduler runnable body (add to your task in Scheduler tab):
 *
 *   ANCIT_App_PreStep();
 *   ACC_step();
 *   ANCIT_App_PostStep();
 */
